-- 036_trap_patterns.sql
-- 카테고리 마스터 시드 테이블: FAR_카테고리_재분류_최종본.md의 94개 항목
-- category: 1=개념선택실수 / 2=무관개념적용 / 3=트리거문구인식실패 / 4=계산절차실수

CREATE TABLE IF NOT EXISTS trap_patterns (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category                smallint NOT NULL CHECK (category BETWEEN 1 AND 4),
  pattern_summary         text NOT NULL,
  distinguishing_rule     text,
  trigger_phrase          text,
  source                  text,
  related_topic_id        text REFERENCES topics(topic_id),
  related_wrong_answer_id uuid REFERENCES wrong_answers(id),
  created_at              timestamptz DEFAULT now()
);

COMMENT ON TABLE trap_patterns IS 'FAR 사고 패턴 카테고리 마스터 — Harry가 topic_id 매칭 시 자주 틀리는 패턴을 사전 경고로 노출';
COMMENT ON COLUMN trap_patterns.category IS '1=개념선택실수 2=무관개념적용 3=트리거문구인식실패 4=계산절차실수';

INSERT INTO trap_patterns (category, pattern_summary, distinguishing_rule, trigger_phrase, source, related_topic_id, related_wrong_answer_id) VALUES
-- 카테고리 1 — 두 개념 다 존재, 어느 걸 적용할지 헷갈림 (37개)
(1, 'LIFO/FIFO 가격 하락기 vs 상승기', '방향 반대 — 하락기 FIFO는 EI·NI 둘 다 낮음', NULL, '채팅방', 'INV_003', NULL),
(1, 'Trading debt security vs Equity security', 'Trading/AFS/HTM은 Debt 전용, Equity엔 없음', NULL, '채팅방', 'INVEST_010', NULL),
(1, 'Consignment inventory 전체 vs 판매분만', '실제 판매된 %만 재고 차감', NULL, '채팅방', 'INV_016', NULL),
(1, 'LCM/LCNRV "effect" vs "answer"', 'effect=NRV−Cost, balance=NRV 그 자체', NULL, '채팅방+QQ7(6/10)', 'INV_006', '74d24dce-06a8-49cb-9b82-54ef369e27ff'),
(1, 'HTM CECL 직접차감 vs Contra account', 'HTM만 직접차감, AFS/AR은 Allowance', NULL, '채팅방', 'INVEST_010', NULL),
(1, 'FIFO/Average(LCNRV) vs LIFO(LCM)', '방법마다 저가법 기준 다름', NULL, '채팅방', 'INV_017', NULL),
(1, 'Equity Method Loss 방향+배당 처리', '둘 다 Investment 차감, 배당은 I/S 아님', NULL, '채팅방+QQ13(6/29)', 'EQM_005', '56506023-bc6e-41b9-9f27-452cf43f3143'),
(1, 'Net Income — 세율 곱셈 vs (1−세율)', 'after-tax 계수는 (1−t)', NULL, '채팅방+QQ1(6/6 EPS)', 'EPS_015', '7035db29-afe5-413a-b5b3-e9b5b1c04384'),
(1, 'PPE Impairment FV vs NRV', 'FV=거래비용 미차감, NRV=차감(Inventory 전용)', NULL, '채팅방 — 반복 실수', 'IMP_001', NULL),
(1, 'Purchase Commitment Loss 본문 vs Notes', 'Notes exhibit 안에 숨어있는 패턴', NULL, '채팅방', NULL, NULL),
(1, 'Moving Average vs Weighted Average', '상승기 Moving > Weighted (같지 않음)', NULL, '채팅방', NULL, NULL),
(1, 'SEC filer 여부 — Subsequent event 공시', 'SEC filer는 평가기간 종료일 공시 면제', NULL, '채팅방', 'DISC_010', NULL),
(1, 'Bond SL vs Effective 상각', 'SL은 매기 고정, Effective만 BV따라 변동', NULL, '채팅방', 'BOND_012', NULL),
(1, 'Purchase discount 미수취 Net vs Gross', 'Net=Interest expense, Gross=이미 재고포함', NULL, '채팅방+QQ8/6(6/17)', NULL, '0211a3d4-d7ec-4321-9bb0-e1aa93690766'),
(1, 'Rehandling charges "Re-" vs Abnormal', 'Re-라서가 아니라 abnormal이라서 비용', NULL, '채팅방', NULL, NULL),
(1, 'Restriction vs Condition (NFP)', 'Barrier 존재 여부', NULL, '채팅방', 'NFP_003', NULL),
(1, 'Fair Value vs NRV', '거래비용 차감 여부', NULL, '채팅방', NULL, NULL),
(1, 'Gross AR vs Net AR', 'Trial balance 계정 vs 표시값', NULL, '채팅방', 'REC_011', NULL),
(1, 'Bond Discount vs Premium 상각 부호', 'Discount는 +, Premium은 −', NULL, '채팅방', 'BOND_012', NULL),
(1, 'Sinking Fund/Debenture vs Serial/Term', '담보·적립금 분류 vs 만기구조 분류', NULL, '채팅방', 'BOND_011', NULL),
(1, 'TDR Ordinary loss vs Restructuring gain', '자산CA−FV vs 부채CA−FV', NULL, '채팅방', 'TDR_001', NULL),
(1, 'Retrospective application vs Restatement', '원칙변경 용어 vs 오류수정 용어', NULL, '채팅방+QQ3(6/25)+텍스트북(cash→accrual)', 'CHANGE_001', 'b25e1662-af2c-4072-8bd5-a8922d197933'),
(1, 'Permanent Fund vs Special Revenue Fund', '원금 사용 가능 여부', NULL, '채팅방', 'GOV_019', NULL),
(1, 'Downstream vs Upstream sale (Consolidation)', 'NCI 영향 여부', NULL, '채팅방+텍스트북', 'CONSOL_002', NULL),
(1, 'Auditing vs Examination', '회계법인 검증 vs 국세청 조사', NULL, '채팅방', NULL, NULL),
(1, 'Time restriction vs Purpose restriction', 'reclassify 트리거가 다름', NULL, '채팅방', 'NFP_001', NULL),
(1, 'Plaintiff vs Defendant', 'Gain/Loss contingency 방향 반대', NULL, '채팅방', 'CONT_001', NULL),
(1, 'Implicit rate vs Incremental borrowing rate', 'Implicit rate 알면 무조건 그것부터', NULL, '채팅방', 'LEASE_017', NULL),
(1, 'Lessee guarantee vs Third-party guarantee', '잔존가치 보증 주체별 Liability 포함 여부', NULL, '채팅방', 'LEASE_016', NULL),
(1, 'Noncumulative vs Cumulative 우선주 배당', '선언 여부 vs 선언 무관 당해분', NULL, '채팅방', 'EPS_002', NULL),
(1, 'Interest paid at par(무변동) vs Payable 증가', '전자=$0 조정, 후자=Payable 변동분만 조정', NULL, 'QQ3/1(6/11)', 'CF_009', '8674a1b4-f9de-41f7-8955-9eb341dba057'),
(1, 'Yield < Coupon vs Yield > Coupon', '전자=Premium, 후자=Discount', NULL, 'QQ20(6/6)', 'BOND_002', '7b851e81-c1aa-4ff4-aef5-7e2503f8c897'),
(1, 'Impairment 3 mechanisms 용어', 'Direct write-down(PPE held for sale) vs FV adjustment(AFS/FVTNI)', NULL, 'QQ15(6/10)', 'IMP_001', '581329a3-17df-4635-8378-9407a4b9079d'),
(1, 'Intraperiod tax allocation — 세전 표시 예외', 'Operating income만 세전, 나머지 전부 net of tax', NULL, 'QQ26(6/6)', NULL, '4359e4b1-4c05-4e72-81f6-7a88f7f407ab'),
(1, 'Change in estimate vs Error correction (RE 영향 여부)', 'Estimate는 RE 안 건드림, Error만 RE 소급수정', NULL, '텍스트북(2599)', 'ACE_001', NULL),
(1, 'Stock 데이터 vs Flow 데이터 누적 방식', 'Stock(EI 등)=마지막 연도가 이미 누적 / Flow(NI 등)=직접 누적 필요', NULL, '텍스트북(2655)', NULL, NULL),
(1, 'Gain on sale — SCF Operating 표시 vs 실제 활동 성격', 'Investing 활동이지만 간접법에서는 Operating 섹션에서 조정', NULL, '텍스트북(2335)', 'CF_009', NULL),
-- 카테고리 2 — 무관한 개념을 잘못 끌어옴 (25개)
(2, 'Equity에 "FV option 미선택" 문구', 'FV option은 Debt 전용, Equity는 원래 무조건 FV', NULL, '채팅방', NULL, NULL),
(2, 'Operating lease에 별도 Interest/Amortization', '단일 blended Lease Expense', NULL, '채팅방', 'LEASE_008', NULL),
(2, 'Callable option = Bondholder 보유', 'Issuer(발행자)가 보유', NULL, '채팅방', NULL, NULL),
(2, 'Lease liability amortization = 전액 원금', '원금+이자 구성, 이자 분리 필요', NULL, '채팅방', 'LEASE_020', NULL),
(2, '"Conditional pledge receivable/revenue" 계정 사용', 'GAAP에 없는 계정 — No Entry가 정답', NULL, '채팅방+QQ10(6/10)', 'NFP_020', '10193755-249d-433b-a79e-3fa107fb752b'),
(2, 'NFP 공사에 "Capital outlay expenditures"', 'Governmental 전용 — NFP는 "Construction in progress"', NULL, '채팅방+QQ12(6/10)', NULL, 'febe7de2-33e9-47e1-9b70-50e051c14fb3'),
(2, 'Restricted cash 직접 지출', 'Satisfaction of use restriction 해제 후 전환 필요', NULL, '채팅방+QQ12(6/10)', NULL, 'febe7de2-33e9-47e1-9b70-50e051c14fb3'),
(2, 'Deferred tax에 영구적 차이 포함', '영구적 차이는 계산에서 처음부터 제외', NULL, '채팅방', 'TAX_002', NULL),
(2, 'T/S(자사주)에 I/S Gain/Loss', 'Owner transaction — APIC/RE로만 처리', NULL, '채팅방', 'EQUITY_004', NULL),
(2, 'UTP Recognition "가정"을 실제 제출로 해석', '순수 내부 평가, 실제 소통 아님', NULL, '채팅방', NULL, NULL),
(2, 'PPE Impairment에 Replacement value', '그런 개념 자체 없음 — FV(exit price) 기준', NULL, '채팅방', 'IMP_001', NULL),
(2, 'Consolidated RE에 Sub 이익 별도 가산', 'Parent RE only — 이미 Equity method 반영됨', NULL, '채팅방+QQ1(6/25)', 'CONSOL_005', 'ed40ff8e-52a9-41c0-802b-20324a5bd6c3'),
(2, 'Intercompany 거래를 지분율만큼만 제거', '지분율 무관 100% 제거', NULL, '채팅방', 'CONSOL_001', NULL),
(2, 'Gain Contingency를 accrual', '항상 $0, 공시만', NULL, '채팅방', 'CONT_001', NULL),
(2, 'Line of credit 한도 자체를 SCF 항목', '실제 차입액만 반영', NULL, '채팅방', NULL, NULL),
(2, 'Notes Receivable(매출대체)을 Investing', '매출 기반 단기 note는 AR과 동일 Operating', NULL, '채팅방', 'CF_014', NULL),
(2, '지분법 투자 연말 FV 재평가', 'No entry — 지분법은 FV 평가 자체 없음', NULL, '채팅방+텍스트북(1434)', 'INVEST_002', NULL),
(2, '지분법 배당을 Investment Income', 'Investment 잔액 감소(원금 회수 개념)', NULL, '채팅방', 'EQM_005', NULL),
(2, 'Discrete project 재고 이자 자본화', 'Becker 기준 재고 이자는 항상 period expense', NULL, 'QQ9(6/17)', NULL, 'c9cc1716-7c6b-42a6-9b76-32cbbb41476a'),
(2, 'Nontaxable proceeds를 tax-basis revenue에서 제외', 'Proceeds는 과세 여부 무관 무조건 revenue 포함', NULL, 'QQ30(6/6)', 'SPF_002', '945abf60-ac89-45e9-a14c-7a7895bf0fad'),
(2, '배당지급(paid on X stock)을 우리 수취로 해석', '"paid on X stock" = X가 자기 주주에게 지급 = 우리와 무관 or Financing 유출(우리 주식이면)', NULL, 'QQ4(6/11)', 'CF_012', 'c48e1fab-38d2-4a18-8773-15493f5eb803'),
(2, '일반 부대비용처럼 발행비(registration fee)도 비용처리', '발행비는 APIC를 차감 (비용 아님)', NULL, '텍스트북(3172)', 'EQUITY_013', NULL),
(2, 'Board designation을 revenue 재분류로 처리', '내부 재분류일 뿐 — revenue 아님', NULL, '텍스트북(2105)', 'NFP_001', NULL),
(2, '지분법 대상 회사 데이터에 지분율 재적용', '이미 Investor 관점 데이터면 지분율 또 곱하면 안 됨', NULL, '텍스트북(1925)', NULL, NULL),
(2, 'Cash basis→Accrual basis 전환을 accounting principle change로 처리', '이건 error correction(restatement)', NULL, '텍스트북(2572)', 'ERR_004', NULL),
-- 카테고리 3 — 인식 실패: 트랩 문구를 못 잡아내는 패턴 (16개)
(3, '"were recorded" (FOB 문제)', '이미 회계처리 끝났다는 뜻 → 복원 분개 필요한데 놓침', 'were recorded', 'QQ4(6/10)', 'INV_015', '4cf8d969-f5cc-4da5-b069-993d979e2394'),
(3, '"Decrease in expense"라는 선지 자체', '비용은 논리적으로 감소할 수 없음 → 선지 자체를 즉시 소거해야 하는데 안 함', 'Decrease in expense', '텍스트북(2105)', NULL, NULL),
(3, '"quarterly payment"라는 단어', '원금+이자 혼합액 → 이자비용 계산에 직접 사용 불가 신호인데 그대로 씀', 'quarterly payment', 'QQ7(6/6 Bond)', 'INT_001', 'a417e3e2-93f0-422a-982e-630319ed0b5f'),
(3, '"no taxable income for the foreseeable future"', 'Valuation Allowance 설정 신호(실현 불가)', 'no taxable income for the foreseeable future', '텍스트북(35010)', 'TAX_004', NULL),
(3, '"more likely than not, NOT to be realized"', '50% 미만 확률 → V/A 설정 신호', 'more likely than not, NOT to be realized', '텍스트북(35010)', 'TAX_004', NULL),
(3, '"at par" + Payable 변동 없음', 'SCF 조정 $0이라는 신호(Expense=Cash 완전 일치)', 'at par', 'QQ3/1(6/11)', 'CF_009', '8674a1b4-f9de-41f7-8955-9eb341dba057'),
(3, 'Bond 반기이자 지급 표시', 'Market/Coupon rate 둘 다 ÷2 해야 하는 신호인데 연율 그대로 사용', 'interest payable June 30 and December 31', 'QQ14(6/6 Bond)', 'BOND_012', 'a40b666e-07f2-4473-8a3f-34c409bbce04'),
(3, '"has an operating cycle of less than 1 year"', '유동/비유동 분류 기준(1년) 신호', 'has an operating cycle of less than 1 year', '텍스트북(847)', NULL, NULL),
(3, '"has taxable income in all years"', 'Valuation Allowance 불필요하다는 신호(DTA 전액 인정)', 'has taxable income in all years', '텍스트북(847)', 'TAX_004', NULL),
(3, '"Dollars and shares in thousands"', '단위 환산 누락 위험 신호', 'Dollars and shares in thousands', '텍스트북(527)', NULL, NULL),
(3, '"Assume treasury stock is not eligible for..."', '특정 계산에서 자사주 제외 지시 — 놓치면 전체 틀림', 'Assume treasury stock is not eligible for', '텍스트북(534)', 'EPS_013', NULL),
(3, '"comparative income statements"', '연도별로 답이 달라질 수 있다는 신호 — 항상 어느 연도인지 재확인', 'comparative income statements', '텍스트북(825)', NULL, NULL),
(3, '"During Year 2 tax rate increased to X%"', '새 거래 없이 기존 누적 잔액 × 증분세율만 조정하라는 신호', 'During Year 2 tax rate increased to X%', '텍스트북(343001)', 'TAX_006', NULL),
(3, 'Income tax basis라는 문구', 'Tax-basis accounting 전용 규칙(proceeds 포함 등) 적용 신호', 'Income tax basis', '텍스트북(2232)', 'SPF_003', NULL),
(3, '여러 임대인/거래처 이름이 동시에 나열', '각각 별도 Unearned revenue 여부 확인 필요 신호', NULL, '텍스트북(2136)', NULL, NULL),
(3, 'x2/x3 등 특정 연도 명시', '"몇 년도 impact"인지 문제마다 다시 확인 필요 — 자동으로 이전 연도 답 재사용 금지', 'x2/x3', '텍스트북(2495)', NULL, NULL),
-- 카테고리 4 — 실수 가능성 높은 절차·계산 패턴 (16개)
(4, '이미 계산된 총액에 비율을 또 곱함 (이중 차감)', 'Total collected가 이미 전체 access 대가면, 추가로 비율 곱하지 않음', NULL, 'QQ1(6/30) — Cougars 문제와 동일 패턴 반복', 'REV_010', '6ef636f7-3f1f-48d9-859b-25104d41710b'),
(4, 'Equity income 계산에 differential amortization 누락', 'NI×지분율에서 초과공정가치 상각분을 반드시 차감', NULL, 'QQ31(6/6)', 'EQM_010', '9aacd27f-315f-477a-b631-d7f1e16f66df'),
(4, 'AFS/Equity 매각 시 실현손익 비교 기준을 취득원가로 착각', '반드시 직전 연말 FV(carrying value)와 비교', NULL, 'QQ7/6(6/6) — 반복', 'INVEST_001', 'd75066c5-86d6-42c9-a1be-60b1ea9da1c1'),
(4, '곱셈/나눗셈 단순 계산 실수 (로직은 맞음)', '최종 숫자 재검산 습관', NULL, 'QQ19(6/28) 113,000×3 계산 오류', 'EPS_013', 'fec0466e-730f-4a03-b657-c52ec9855bac'),
(4, '배당 한도(RE) 계산 후 초과분을 return of capital로 처리 안 함', '총배당 − 배당한도 = Investment 차감(원금 회수)', NULL, 'QQ2(6/6)', 'EQM_003', '6b73fdad-0f0c-4d2b-b42e-c93771a3e8cd'),
(4, 'AFS OCI 계산에서 여러 종목 합산 누락', '손상 후 회복분은 종목별로 각각 계산 후 합산', NULL, 'QQ23(6/28)', NULL, 'a2379780-6129-4287-82f6-6e97dbb62baa'),
(4, 'Prior period error를 당기 계정으로만 처리', '전기분=RE 직접수정 / 당기분=I/S 계정, 반드시 분리', NULL, 'QQ3(6/25)', 'CHANGE_003', 'b25e1662-af2c-4072-8bd5-a8922d197933'),
(4, 'SE Statement의 net of tax 대상 항목 암기 불완전', 'Correction of errors / Change in principle / OCI = net of tax 필요, Change in estimate는 SE에 없음', NULL, 'QQ2(6/25)', NULL, '4ab13806-9b0c-4221-b176-5d0bd8a2ea09'),
(4, '보수주의 원칙 4축 중 일부만 기억', '자산↑방지 / 손실즉시 / 이익실현시만 / 부채↓방지(누락 잦음)', NULL, 'QQ14(6/10)', NULL, 'f8b43076-bf41-4b20-a2a7-c1dfce78d506'),
(4, '비현금 거래(주식+현금 혼합 취득)를 전액 Investing으로 처리', '현금 지급분만 Investing, 나머지는 Supplemental disclosure', NULL, 'QQ7(6/11)', 'CF_011', '4a3254f5-d72c-41da-8dfb-0936aa73d6d3'),
(4, '전기에 이미 현금화된 항목을 당기 SCF에 재포함', '당해 연도 실제 현금 이동분만 계산 (전기분 제외)', NULL, 'QQ6(6/11)', 'CF_014', '60d2f36c-f6cc-40b0-bca8-c38193facede'),
(4, 'Goodwill 계산 시 기초 시점 BV 사용', '반드시 취득 시점(예: 7/1) BV 사용', NULL, '텍스트북(1788)', 'BC_001', NULL),
(4, 'Consolidated SE 계산 시 NCI 별도 계산 생략', 'Parent SE + NCI(기초+NI지분−배당지분) 별도 계산 후 합산', NULL, 'QQ1(6/25 Consol)', 'CONSOL_005', 'ed40ff8e-52a9-41c0-802b-20324a5bd6c3'),
(4, 'Loan Receivable/Payable을 netting해서 SCF 기입', '빌려준 것과 회수한 것 절대 netting 금지, in/out 각각 기입', NULL, '텍스트북(2468)', NULL, NULL),
(4, 'JE 역산 시 Valuation Allowance를 Cr 합산에서 누락', 'V/A는 Cr 항목이므로 Dr/Cr 균형 맞출 때 반드시 포함', NULL, '텍스트북(343000)', 'TAX_009', NULL),
(4, 'Modified cash basis 전환 시 CGS 처리 재계산 누락', '현금주의 구매액을 그대로 쓰지 않고 CGS로 재계산', NULL, '텍스트북(2208)', NULL, NULL);
